### ISSUE TITLE
Unable to plot the Calendar in Slidify

### ISSUE THREAD

**Issue by hetong007** [ramnathv/rChartsCalendar#2]
After the suggested installation code(the dev branch), I simply run the example code in Slidify:

``` r
dat <- read.csv('data/paul_george_rs_data.csv')[,c('date', 'pts')]
library(rChartsCalendar)
library(rCharts)
r1 <- plotCalMap(x = 'date', y = 'pts',
  data = dat, 
  domain = 'month',
  start = "2012-10-27",
  legend = seq(10, 50, 10),
  itemName = 'point',
  range = 7
)
r1
```

In the Markdown file it turns to be

```
## Warning: cannot open file 'assets/fig/unnamed-chunk-3.html': No such file
## or directory
```

```
## Error: cannot open the connection
```

I can plot it in the R environment. Is there something wrong with knitr and rCharts?

``` r
> sessionInfo()
R version 3.1.0 (2014-04-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)

locale:
[1] LC_COLLATE=Chinese (Simplified)_People's Republic of China.936 
[2] LC_CTYPE=Chinese (Simplified)_People's Republic of China.936   
[3] LC_MONETARY=Chinese (Simplified)_People's Republic of China.936
[4] LC_NUMERIC=C                                                   
[5] LC_TIME=Chinese (Simplified)_People's Republic of China.936    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rCharts_0.4.5       rChartsCalendar_0.1 slidify_0.4.5       knitr_1.6          

loaded via a namespace (and not attached):
 [1] codetools_0.2-8 digest_0.6.4    evaluate_0.5.5  formatR_0.10    grid_3.1.0      lattice_0.20-29
 [7] markdown_0.7    plyr_1.8.1      Rcpp_0.11.2     RJSONIO_1.2-0.2 stringr_0.6.2   tools_3.1.0    
[13] whisker_0.3-2   yaml_2.1.11    
```

**Comment by ramnathv** [comment]
I think this error occurs because you dont have a folder named `assets`. If you initialized your slide deck with the `author` function, it will automatically create these folders for you. So I would suggest that you try slidifying the deck after adding an `assets` folder to your working directory.

**Comment by hetong007** [comment]
Thank you for your reply.

I used the `author` function and there's no error now, instead it generates the following html codes in the `md` file. 

<pre><code>```
## &lt;iframe src=&#39; assets/fig/unnamed-chunk-3.html &#39; scrolling=&#39;no&#39; frameBorder=&#39;0&#39; seamless class=&#39;rChart D:/R/R-3.1.0/library/rChartsCalendar/calmap &#39; id=iframe- chart19007d3046c5 &gt;&lt;/iframe&gt; &lt;style&gt;iframe.rChart{ width: 100%; height: 400px;}&lt;/style&gt;
```</code></pre>

Which means It is not properly parsed in the `html` file: the `html` file wrap this piece of code in `<pre><code>` . Therefore it failed to actually wrap the graph in the page.

After I manually replace the `<pre>` part with the actual code, it is great.

**Comment by ramnathv** [comment]
`knitr` by default comments all output with `##` and puts it into a code block. You need to use chunk options to disable this behavior. So, for chunks that output rCharts iframes, make sure you set `comment = NA` and `results = "asis"`. For example

``````
```{r comment = NA, results = "asis"}
library(rCharts)
r1 <- rPlot(mpg ~ wt, data = mtcars, type = 'point')
r1
```
``````

**Comment by hetong007** [comment]
I understand. Thank you for your guidance. The result is great.
